### ISSUE TITLE
LLDB fails to start on the cloud dev machines

### ISSUE THREAD

**Issue by jyn514** [rust-lang/simpleinfra#254]
```
> lldb --version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
lldb version 14.0.0
> x t tests/debuginfo/basic-types-globals-metadata.rs
Check compiletest suite=debuginfo mode=debuginfo (aarch64-unknown-linux-gnu -> aarch64-unknown-linux-gnu)

running 2 tests
iF
failures:

---- [debuginfo-lldb] tests/debuginfo/basic-types-globals-metadata.rs stdout ----
NOTE: compiletest thinks it is using LLDB version 1400
NOTE: compiletest thinks it is using LLDB without native rust support

error: Error while running LLDB
status: exit status: 1
command: PYTHONPATH="/usr/lib/local/lib/python3.10/dist-packages" PYTHONUNBUFFERED="1" "/usr/bin/python3" "/home/gh-jyn514/rust/src/etc/lldb_batchmode.py" "/home/gh-jyn514/rust/build/aarch64-unknown-linux-gnu/test/debuginfo/basic-types-globals-metadata.lldb/a" "/home/gh-jyn514/rust/build/aarch64-unknown-linux-gnu/test/debuginfo/basic-types-globals-metadata.lldb/basic-types-globals-metadata.debugger.script"
--- stdout -------------------------------
LLDB batch-mode script
----------------------
Debugger commands script is '/home/gh-jyn514/rust/build/aarch64-unknown-linux-gnu/test/debuginfo/basic-types-globals-metadata.lldb/basic-types-globals-metadata.debugger.script'.
Target executable is '/home/gh-jyn514/rust/build/aarch64-unknown-linux-gnu/test/debuginfo/basic-types-globals-metadata.lldb/a'.
Current working directory is '/home/gh-jyn514/rust'
------------------------------------------
--- stderr -------------------------------
Traceback (most recent call last):
  File "/home/gh-jyn514/rust/src/etc/lldb_batchmode.py", line 184, in <module>
    debugger = lldb.SBDebugger.Create()
AttributeError: module 'lldb' has no attribute 'SBDebugger'
------------------------------------------
```

This is because of https://github.com/llvm/llvm-project/issues/55575 I think, but setting PYTHONPATH=/usr/lib/llvm-14/lib/python3.10/dist-packages doesn't seem to have helped.

**Comment by albertlarsan68** [comment]
I got another workaround working at some point, but I think it is lost through my history file.
I will search it.

**Comment by albertlarsan68** [comment]
If you have the `PYTHONPATH` env containing `/usr/lib/llvm-14/lib/python3.10/dist-packages`, then (for now) it works (I tested on the `eu-2` instance (x86_64))

**Comment by albertlarsan68** [comment]
There is a sudo-needing workaround in https://github.com/llvm/llvm-project/issues/55575#issuecomment-1379470228, and I posted the non-sudo in https://github.com/llvm/llvm-project/issues/55575#issuecomment-1415404891.
